dist: bionic
language: csharp
dotnet: "3.1"
mono: none

script:
 - dotnet restore
 - dotnet build
 - dotnet pack -c Release
 - ./scripts/test_files_are_importable_by_msbuild.rb
 - 'unzip -l bin/Release/*.nupkg'
