name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack CodeStyle/CodeStyle.csproj --configuration Release --no-restore --output nupkg
    - name: Test that files are importable by MSBuild
      run: dotnet fsi scripts/test-files-are-importable-by-msbuild.fsx
    - name: Show NuGet package content
      run: unzip -l nupkg/*.nupkg
