name: Build LaTeX

on:
  pull_request:
    branches:
      - master
    # paths:
    #   - 'documentation/**'
  push:
    branches:
      - master
    paths:
      - 'documentation/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install LaTeX
      run: sudo apt-get install texlive-latex-extra texlive-lang-german texlive-fonts-extra latexmk
    - name: Run latexmk
      run: latexmk -pdf
      working-directory: documentation
    - name: Upload generated PDF
      uses: actions/upload-artifact@v1
      with:
        name: guidelines.pdf
        path: 'documentation/C-Sharp Coding Guidelines.pdf'
    - name: Copy PDF to publish directory
      run: 'mkdir public && cp "documentation/C-Sharp Coding Guidelines.pdf" public/c-sharp-coding-guidelines.pdf'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: success() && github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
